repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: trailing-whitespace

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
    args: [--application-directories=.:torweather, --py39-plus]

- repo: https://github.com/psf/black
  rev: "22.1.0"
  hooks:
  - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.941
  hooks:
  - id: mypy
    args: [--ignore-missing-imports]
